@startuml members_agenda_api.services.personservice.add_member_to_slot-component
skinparam BoxPadding 10
skinparam componentStyle rectangle

rectangle None #line:transparent;text:transparent {
  package members_agenda_api {
    package services {
      package personservice {
        frame PersonService {
          [members_agenda_api.services.personservice.PersonService.add_member_to_slot] as "add_member_to_slot" << @trace_to_component_puml >>
        }
      }
      package dataservice {
        frame DataService {
          [members_agenda_api.services.dataservice.DataService.get_person] as "get_person"
          [members_agenda_api.services.dataservice.DataService._prepared_query] as "_prepared_query"
          [members_agenda_api.services.dataservice.DataService.get_slot_with_members] as "get_slot_with_members"
          [members_agenda_api.services.dataservice.DataService.get_active_slots_and_events] as "get_active_slots_and_events"
        }
      }
    }
  }
  package fastapi {
    frame encoders {
      [fastapi.encoders.jsonable_encoder] as "jsonable_encoder"
    }
    frame _compat {
      [fastapi._compat._model_dump] as "_model_dump"
    }
  }
}
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] -> [members_agenda_api.services.dataservice.DataService.get_person] : 1
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] <. [members_agenda_api.services.dataservice.DataService.get_person] : 4
[members_agenda_api.services.dataservice.DataService.get_person] --> [members_agenda_api.services.dataservice.DataService._prepared_query] : 2
[members_agenda_api.services.dataservice.DataService.get_person] <.. [members_agenda_api.services.dataservice.DataService._prepared_query] : 3
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] -> [members_agenda_api.services.dataservice.DataService.get_slot_with_members] : 5
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] <. [members_agenda_api.services.dataservice.DataService.get_slot_with_members] : 8
[members_agenda_api.services.dataservice.DataService.get_slot_with_members] --> [members_agenda_api.services.dataservice.DataService._prepared_query] : 6
[members_agenda_api.services.dataservice.DataService.get_slot_with_members] <.. [members_agenda_api.services.dataservice.DataService._prepared_query] : 7
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] -> [members_agenda_api.services.dataservice.DataService.get_active_slots_and_events] : 9
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] <. [members_agenda_api.services.dataservice.DataService.get_active_slots_and_events] : 14
[members_agenda_api.services.dataservice.DataService.get_active_slots_and_events] --> [members_agenda_api.services.dataservice.DataService._prepared_query] : 10, 12
[members_agenda_api.services.dataservice.DataService.get_active_slots_and_events] <.. [members_agenda_api.services.dataservice.DataService._prepared_query] : 11, 13
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] -> [fastapi.encoders.jsonable_encoder] : 15
[members_agenda_api.services.personservice.PersonService.add_member_to_slot] <. [fastapi.encoders.jsonable_encoder] : 54
[fastapi.encoders.jsonable_encoder] -> [fastapi._compat._model_dump] : 16
[fastapi.encoders.jsonable_encoder] <. [fastapi._compat._model_dump] : 17
[fastapi.encoders.jsonable_encoder] -> [fastapi.encoders.jsonable_encoder] : 18, 19, 21 ... 45, 47, 49

footer Generated by //pydoctrace//
@enduml
